#!/usr/bin/env python3
"""gen_perf_tests.py -- generate branch-predictor PERFORMANCE characterization tests.

Writes into this directory:
  test_h1..h6.S  BTB capacity sweep: N distinct always-taken branches,
                 N in {16,32,64,96,128,256}  ((N-1) kernel + 1 loop branch)
  test_h7.S      BTB conflict thrash: 63 branches sharing one BTB index
                 (256-byte spacing), + 1 loop branch elsewhere
  test_i1.S      BHT, no aliasing: 64 branches (32 taken / 32 never-taken),
                 all on distinct BHT entries
  test_i2.S      BHT, destructive aliasing: 32 taken/never-taken pairs sharing
                 BHT entries (2048-byte spacing)
  test_j1..j3.S  randomized branch outcomes, P(taken) in {0.1, 0.5, 0.9},
                 seeded PRNG, 16384 outcomes each

Conventions (match the existing a..g tests):
  - .option norvc everywhere: every instruction is 4 bytes, PC layout exact.
  - Report ids: 1 = delta branches (0x7C0), 2 = delta mispredicts (0x7C1),
                 3 = checksum (t0==0, or t6 popcount for j-tests).
  - BTB index = PC[7:2] (64 entries, direct-mapped, tag PC[31:8]).
  - BHT index = PC[10:2] (512 entries, 2-bit counters, reset weakly-NT).
  - A BTB miss predicts not-taken; BTB allocates only on taken control-flow.
  - The countdown `addi` is placed FIRST in the loop so the loop branch lands
    on BTB index (N&63), keeping all N indices distinct for N <= 64.

All layout properties below are expressed as RELATIVE offsets, so they hold
for any base PC. The generator asserts them before writing each file.
"""
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
ITERS = 200          # loop iterations for h/i tests
WORDS = 512          # fuzz table size in words -> 16384 branch outcomes
J_SEEDS = {0.1: 12345, 0.5: 67890, 0.9: 13579}


def btb_idx_rel(off):
    """BTB index bits of a PC at relative byte offset off (base-independent)."""
    return (off // 4) & 63


def bht_idx_rel(off):
    """BHT index bits of a PC at relative byte offset off (base-independent)."""
    return (off // 4) & 511


HDR = """\
// {name} -- {desc}
// Generated by gen_perf_tests.py -- DO NOT EDIT BY HAND.
#include "common.inc"
    .option norvc
    HDR
    SNAPSHOT s1, s2
"""

TAIL_T0 = """\
    csrr t1, 0x7C0
    csrr t2, 0x7C1
    sub s1, t1, s1
    sub s2, t2, s2
    REPORT 1, s1
    REPORT 2, s2
    REPORT 3, t0
    PASS
    TAIL
"""


def write(name, body):
    path = os.path.join(HERE, name)
    with open(path, "w") as f:
        f.write(body)
    print(f"wrote {name}")


# ---------------------------------------------------------------- group h
# BTB capacity sweep. addi first, then kernel branch i at rel 4*(i+1)
# (i = 0..N-2), loop bne at rel 4*N: N consecutive BTB indices,
# distinct iff N <= 64.
def gen_h(tag, n):
    assert 2 <= n <= 256
    lines = [HDR.format(name=f"test_{tag}.S",
                        desc=f"BTB capacity: {n} distinct always-taken branches")]
    lines.append(f"    li t0, {ITERS}\nouter:\n    addi t0, t0, -1\n")
    for i in range(n - 1):
        lines.append(f"    beq x0, x0, .Lk{i + 1}\n.Lk{i + 1}:\n")
    lines.append("    bne t0, x0, outer\n")
    lines.append(TAIL_T0)
    kidx = [btb_idx_rel(4 * (i + 1)) for i in range(n - 1)]
    lidx = btb_idx_rel(4 * n)
    if n <= 64:
        assert len(set(kidx + [lidx])) == n, f"{tag}: BTB indices not distinct"
    hidx = [bht_idx_rel(4 * (i + 1)) for i in range(n - 1)] + [bht_idx_rel(4 * n)]
    assert len(set(hidx)) == n, f"{tag}: BHT indices not distinct"
    write(f"test_{tag}.S", "".join(lines))


# h7: BTB conflict thrash. 63 kernel branches at 256B spacing -> all share
# BTB index ((64*i)&63 == 0 relative), distinct tags -> every access misses.
# Loop branch (addi at +4, bne at +8 after last slot) -> index 2, no clash.
def gen_h7():
    nker = 63
    lines = [HDR.format(name="test_h7.S",
                        desc="BTB conflict thrash: 63 branches, one BTB index")]
    lines.append(f"    li t0, {ITERS}\n")
    lines.append("slot_0:\n")
    for i in range(nker):
        tgt = f"slot_{i + 1}" if i + 1 < nker else "loop_back"
        lines.append(f"    beq x0, x0, {tgt}\n")
        if i + 1 < nker:
            lines.append(f"    .space 252\nslot_{i + 1}:\n")
        else:
            lines.append("    .space 252\n")
    lines.append("loop_back:\n    addi t0, t0, -1\n    bne t0, x0, slot_0\n")
    lines.append(TAIL_T0)
    kidx = [btb_idx_rel(256 * i) for i in range(nker)]
    assert len(set(kidx)) == 1, "h7: kernel BTB indices not all equal"
    # loop bne is 8B past slot_62's branch (4B branch + 252 space + addi)
    # NOTE: the loop `bne` spans -16132B, beyond the B-type +/-4KiB range, so
    # the assembler emits beqz+jal. Both are modeled in check_perf.trace_h7.
    loop_bne_rel = 256 * nker + 4
    lidx = btb_idx_rel(loop_bne_rel)
    assert lidx != kidx[0], "h7: loop branch collides with kernel BTB index"
    kh = set(bht_idx_rel(256 * i) for i in range(nker))
    assert bht_idx_rel(loop_bne_rel) not in kh, "h7: loop BHT alias"
    assert btb_idx_rel(loop_bne_rel + 4) not in (kidx[0], lidx), \
        "h7: assembler jal collides in BTB"
    assert bht_idx_rel(loop_bne_rel + 4) not in kh, "h7: assembler jal BHT alias"
    write("test_h7.S", "".join(lines))


# ---------------------------------------------------------------- group i
# i1: no aliasing. T_i (always taken) at 8i, N_i (never taken) at 8i+4.
# 64 consecutive BHT entries. Loop bne at rel 260 -> BTB idx 1 (odd),
# T branches at even indices -> distinct.
def gen_i1():
    npair = 32
    lines = [HDR.format(name="test_i1.S",
                        desc="BHT no-alias control: 32T/32N, distinct entries")]
    lines.append(f"    li t0, {ITERS}\nouter:\n")
    for i in range(npair):
        lines.append(f"    beq x0, x0, .Lt{i}\n.Lt{i}:\n")
        lines.append(f"    bne x0, x0, .Ln{i}\n.Ln{i}:\n")
    lines.append("    addi t0, t0, -1\n    bne t0, x0, outer\n")
    lines.append(TAIL_T0)
    hidx = []
    for i in range(npair):
        hidx += [bht_idx_rel(8 * i), bht_idx_rel(8 * i + 4)]
    assert len(set(hidx)) == 64, "i1: BHT indices not distinct"
    assert bht_idx_rel(260) not in set(hidx), "i1: loop BHT alias"
    tidx = [btb_idx_rel(8 * i) for i in range(npair)]
    assert len(set(tidx)) == npair and all(t % 2 == 0 for t in tidx)
    assert btb_idx_rel(260) not in set(tidx), "i1: loop BTB collision"
    assert btb_idx_rel(260) % 2 == 1, "i1: loop BTB index not odd"
    write("test_i1.S", "".join(lines))


# i2: destructive aliasing. T_i at 4i, N_i at 2048+4i share BHT entry i.
# T_31 jumps straight to the N block; the loop branch sits right after the
# N block, so no trampoline jump is needed.
def gen_i2():
    npair = 32
    lines = [HDR.format(name="test_i2.S",
                        desc="BHT destructive alias: 32 T/N pairs share entries")]
    lines.append(f"    li t0, {ITERS}\nouter:\n")
    for i in range(npair):
        tgt = "nblock" if i == npair - 1 else f".Lt{i + 1}"
        lines.append(f"    beq x0, x0, {tgt}\n.Lt{i + 1}:\n")
    # T block is 128B; pad with zeros (never executed) up to rel 2048.
    lines.append("    .space 1920\nnblock:\n")
    for i in range(npair):
        lines.append(f"    bne x0, x0, .Ln{i}\n.Ln{i}:\n")
    lines.append("    addi t0, t0, -1\n    bne t0, x0, outer\n")
    lines.append(TAIL_T0)
    for i in range(npair):
        assert bht_idx_rel(4 * i) == bht_idx_rel(2048 + 4 * i), \
            "i2: pair does not share BHT entry"
    pair_entries = set(bht_idx_rel(4 * i) for i in range(npair))
    assert len(pair_entries) == npair, "i2: pairs alias each other"
    tidx = [btb_idx_rel(4 * i) for i in range(npair)]
    assert len(set(tidx)) == npair, "i2: T BTB indices not distinct"
    # loop bne is 4B past the N block end (2176 addi + 2180 bne)
    assert btb_idx_rel(2180) not in set(tidx), "i2: loop BTB collision"
    assert bht_idx_rel(2180) not in pair_entries, "i2: loop BHT alias"
    write("test_i2.S", "".join(lines))


# ---------------------------------------------------------------- group j
# Randomized outcomes vs 2-bit-counter theory. One random branch
# (beq t3,x0,.Lnt -- taken iff outcome bit == 0), inner/outer loop branches.
# Table: WORDS words, 32 outcomes each, LSB first.
def gen_j(tag, p):
    seed = J_SEEDS[p]
    rng = random.Random(seed)
    n = 32 * WORDS
    words = []
    ones = 0
    for _ in range(WORDS):
        w = 0
        for k in range(32):
            bit = 0 if rng.random() < p else 1   # bit==0 -> branch taken
            w |= bit << k
            ones += bit
        words.append(w)
    taken = n - ones
    lines = [HDR.format(
        name=f"test_{tag}.S",
        desc=f"fuzz P(taken)={p}, seed={seed}, {n} outcomes")]
    lines.append("    la t0, outcomes\n")
    lines.append(f"    li t4, {WORDS}\n    li s3, 0\nouter:\n")
    lines += [
        "    lw t2, 0(t0)\n",
        "    addi t0, t0, 4\n",
        "    li t5, 32\n",
        "inner:\n",
        "    andi t3, t2, 1\n",
        "    srli t2, t2, 1\n",
        "    beq t3, x0, .Lnt\n",   # THE random branch: taken iff bit==0
        "    addi s3, s3, 1\n",     # bit==1 (not-taken outcome): popcount -> s3
        ".Lnt:\n",
        "    addi t5, t5, -1\n",
        "    bne t5, x0, inner\n",
        "    addi t4, t4, -1\n",
        "    bne t4, x0, outer\n",
    ]
    lines += [
        "    csrr t1, 0x7C0\n",
        "    csrr t2, 0x7C1\n",
        "    sub s1, t1, s1\n",
        "    sub s2, t2, s2\n",
        "    REPORT 1, s1\n",
        "    REPORT 2, s2\n",
        # s3, not t6: REPORT uses t6 as scratch, so REPORT 1/2 would destroy
        # a t6-held checksum before REPORT 3 runs. s3 is callee-saved.
        "    REPORT 3, s3\n",
        "    PASS\n",
        "    TAIL\n",
        '    .section .rodata, "a", @progbits\n',
        "    .align 2\n",
        "outcomes:\n",
    ]
    for w in words:
        lines.append(f"    .word 0x{w:08x}\n")
    # random/inner/outer branches are 8/20/28 bytes past `inner`
    # (see annotated offsets above): distinct BTB and BHT indices.
    idxs = [btb_idx_rel(8), btb_idx_rel(20), btb_idx_rel(28)]
    assert len(set(idxs)) == 3, f"{tag}: fuzz BTB indices collide"
    hidx = [bht_idx_rel(8), bht_idx_rel(20), bht_idx_rel(28)]
    assert len(set(hidx)) == 3, f"{tag}: fuzz BHT indices collide"
    write(f"test_{tag}.S", "".join(lines))
    return {"p": p, "seed": seed, "n": n, "taken": taken, "ones": ones}


def main():
    info = {}
    for tag, n in [("h1", 16), ("h2", 32), ("h3", 64),
                   ("h4", 96), ("h5", 128), ("h6", 256)]:
        gen_h(tag, n)
        info[tag] = n
    gen_h7()
    gen_i1()
    gen_i2()
    for tag, p in [("j1", 0.1), ("j2", 0.5), ("j3", 0.9)]:
        ji = gen_j(tag, p)
        info[tag] = ji
        print(f"  {tag}: P(taken)={p} seed={ji['seed']} "
              f"outcomes={ji['n']} taken={ji['taken']} ones(t6)={ji['ones']}")
    print("all layout assertions passed")


if __name__ == "__main__":
    main()
